config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "pins/index"
  get 'static_pages/home'
  get 'static_pages/about'
  resources :pins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
    has_one_attached :image
    has_many_attached :pictures
    has_rich_text :body

    def image_as_thumbnail
        return unless image.content_type.in?(%w[image/jpeg image/png])
        image.variant(resize_to_limit: [300, 300]).processed
    end

    def pictures_as_thumbnails
        pictures.map do |picture|
            picture.variant(resize_to_limit: [150, 150]).processed
        end
    end

    def picture_as_thumbnail(pic)
        pic.variant(resize_to_limit: [200, 200]).processed
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :title, :image, pictures: [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyPhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto my-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, class: "contents") do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p class="flex">
    <strong class="flex font-medium text-lg mr-4 italic">Title:</strong>
    <p class="text-3xl tracking-wider text-[#efe565]] underline mb-4"><%= pin.title %></p>
  </p>

  <div class="border-2 rounded-xl border-gray-600 p-6 mb-16">
    <%= pin.body %> 
   

    <br />
    <div class="w-fill py-5 border-2 rounded-xl shadow-md shadow-gray-300 flex justify-center">
      <% if pin.image.content_type.in?(%w[image/jpeg image/png]) %>
        <%= link_to image_tag(pin.image_as_thumbnail), pin.image if pin.image.attached? %>
      <% end %>
    </div>
    <br />
    <hr />
    <br />

    <div class="grid grid-cols-6 gap-8">
      <% pin.pictures.each do |picture| %> 
      <div class="w-fill border-2 rounded-xl shadow-lg shadow-gray-400 flex justify-center">
        <%= link_to image_tag(pin.picture_as_thumbnail(picture)), picture %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pin</h1>

  <%= render "form", pin: @pin %>

  <%= link_to "Show this pin", @pin, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pins", pins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pins/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="justify-center items-center">
    <h1 class="text-4xl uppercase tracking-wider text-gray-600 font-sans pb-4">Entries</h1>
    <%= link_to 'New Entry', new_pin_path, class: "max-w-full rounded-lg shadow-sm shadow-black mb-4 py-1 w-[11%] bg-[#f5f5f5] text-lg text-black-40 text-center hover:bg-[#565efe] block font-medium font-sans" %>
  </div>

  <div id="pins" class="min-w-fill pt-16 flex-grid grid-cols-2 gap-y-20">
    <%= render @pins %>
  </div>
</div>

app/views/pins/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pin</h1>

  <%= render "form", pin: @pin %>

  <%= link_to 'Back to pins', pins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pins/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pin %>

    <%= link_to 'Edit this pin', edit_pin_path(@pin), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this pin', pin_path(@pin), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to pins', pins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/static_pages/about.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#about</h1>
  <p>Find me in app/views/static_pages/about.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<div class="px-28">
  <h1 class="font-bold text-6xl pb-8">My Family in Motion</h1>
  <p class="text-lg tracking-wide mb-2">This is a simple Application I created for friends and family to follow
     along with us as we grow together.  There will be many stops and milestones
     along the way so buckle up and hold on tight.
  </p>

  <p class="text-lg tracking-wide mb-24">Be sure to keep all hands, feet, and tails inside the space-craft at all times!</p>
  <div class="mb-8 flex justify-center shadow-xl shandow-gray-400 opacity-90">
    <%= image_tag "gpa_maya.jpg", width: 500 %>
  </div>
  <div>
    <p class="italic text-lg">"The family is one of nature's masterpieces."</p>
    <p class="font-bold px-2">-George Santayana, <span class="text-sm font-light">Philosopher</span></p>
  </div>
</div>